name: Android CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.1